### ISSUE TITLE
Home page for website - dead 

### ISSUE THREAD

**Issue by mallond** [jimhigson/oboe.js#103]
Does not lead to credibility of this product. Although, 3858 stars - what gives?

**Comment by jimhigson** [comment]
Hi yes, the hosing on Nodejitsu has been a problem recently. Even more of a
problem is my lack of time due to projects which pay me money :-) if you
have time to help migrate away from jitsu I'd be more than grateful

**Comment by JuanCaicedo** [comment]
Yep, this is mentioned in #102 and https://github.com/jimhigson/oboe.js-website/issues/20. Working on it :)

**Comment by pferdefleisch** [comment]
If you found this issue, like me, here's the link to @JuanCaicedo's temporary version http://www.juancaicedo.com/oboe.js-website/
The library looks pretty neat. Thanks @jimhigson and @JuanCaicedo

**Comment by JuanCaicedo** [comment]
Given that there have been no problems since the last time Jim did some stuff, I'm going to close this
