### ISSUE TITLE
Reading json array

### ISSUE THREAD

**Issue by rajashekhargundeti** [jimhigson/oboe.js#106]
I have huge data in my json file as below:
Its an array with lot of records:
[
   {
        "RECORD_TYPE_CD": "D",
        "SOURCE_SITE_CD": 5200,
        "REFERENCE_DT": 20160329,
        "PRODUCT_LINE_CD": "SY",
        "PART_NR": "392512-236",
        "REGION_CD": "AM",
        "LOCATION_CD": "WI04",
        "AVAILABLE_QT": 506
    },
    {
        "RECORD_TYPE_CD": "D",
        "SOURCE_SITE_CD": 5200,
        "REFERENCE_DT": 20160329,
        "PRODUCT_LINE_CD": "SY",
        "PART_NR": "44.5Q401.011",
        "REGION_CD": "AM",
        "LOCATION_CD": "WI04",
        "AVAILABLE_QT": 946
    },
....
]

I can't read all data into memory or sometime it may be coming from a client.
I would like to read one record at a time from this source, how can i do this with your module?

I tried as below:

var oboe = require('oboe');
var fs = require('fs');
oboe(fs.createReadStream('9428.json')).node('*',function(thing) {
	console.log("item:" + JSON.stringify(thing));
}).done(function(things) {
	console.log('Done');
})

but it is giving the output as below:

C:\workspace\nodejs\test2>node test2.js
item:"D"
item:5200
item:20160329
item:"SY"
item:"392512-236"
item:"AM"
item:"WI04"
item:506
item:{"RECORD_TYPE_CD":"D","SOURCE_SITE_CD":5200,"REFERENCE_DT":20160329,"PRODUCT_LINE_CD":"SY","PART_NR":"392512-236","REGION_CD":"AM","LOCATION_CD":"WI04","AVAILABLE_QT
":506}
item:"D"
item:5200
item:20160329
item:"SY"
item:"44.5Q401.011"
item:"AM"
item:"WI04"
item:946
item:{"RECORD_TYPE_CD":"D","SOURCE_SITE_CD":5200,"REFERENCE_DT":20160329,"PRODUCT_LINE_CD":"SY","PART_NR":"44.5Q401.011","REGION_CD":"AM","LOCATION_CD":"WI04","AVAILABLE_
QT":946}
item:[{"RECORD_TYPE_CD":"D","SOURCE_SITE_CD":5200,"REFERENCE_DT":20160329,"PRODUCT_LINE_CD":"SY","PART_NR":"392512-236","REGION_CD":"AM","LOCATION_CD":"WI04","AVAILABLE_Q
T":506},{"RECORD_TYPE_CD":"D","SOURCE_SITE_CD":5200,"REFERENCE_DT":20160329,"PRODUCT_LINE_CD":"SY","PART_NR":"44.5Q401.011","REGION_CD":"AM","LOCATION_CD":"WI04","AVAILAB
LE_QT":946},...]

Please let me know how to solve/use this

**Comment by JuanCaicedo** [comment]
Glad to hear you're looking at Oboe @rajashekhargundeti! I think this question is a better fit for stackoverflow, could you please ask it there and use the tag `oboe.js`? I'll take the time to respond 😃
