### ISSUE TITLE
oboe docs are not accessible

### ISSUE THREAD

**Issue by vijayreddygudi** [jimhigson/oboe.js#107]
I was trying to access http://oboejs.com/ for docs. It seems it is down. Can anyone help with this.
![oboe docs](https://cloud.githubusercontent.com/assets/5565328/15577607/38f1e654-232b-11e6-99da-db31e7af6b8c.png)

**Comment by vijayreddygudi** [comment]
There is an open issue https://github.com/jimhigson/oboe.js/issues/103 Closing this.

**Comment by JuanCaicedo** [comment]
While we fix this, you can see the docs at http://www.juancaicedo.com/oboe.js-website/

**Comment by vijayreddygudi** [comment]
Thanks @JuanCaicedo.
