### ISSUE TITLE
oboe.js domain expired

### ISSUE THREAD

**Issue by nmeegama** [jimhigson/oboe.js#118]
The oboe.js domain (http://oboejs.com/) is not working anymore.

**Comment by JuanCaicedo** [comment]
Thanks for flagging, feel free to use http://www.juancaicedo.com/oboe.js-website/ in the meantime :)

**Comment by JuanCaicedo** [comment]
I don't have the ability to renew the domain, only @jimhigson does. Please keep using the other link for now 😕

**Comment by jimhigson** [comment]
I have just renewed the domain (until 2020) - should be available again as soon as the inter-tubes catch up. I'll leave this ticket here until I can see the site again.

**Comment by JuanCaicedo** [comment]
Website is back up, thanks @jimhigson!

**Comment by nmeegama** [comment]
Thanks the library saved me some time
