### ISSUE TITLE
Standardize style

### ISSUE THREAD

**Issue by JuanCaicedo** [jimhigson/oboe.js#123]
Having consistent indentation, formatting, etc, does wonders for readability. I would advocate for something like https://github.com/feross/standard instead of having to pick conventions

**Comment by JuanCaicedo** [comment]
I've also been using https://github.com/prettier/prettier/ on other projects and really like how it works. I often see it paired with https://github.com/okonet/lint-staged which runs on every commit, to ensure everyone follows the same style

**Comment by JuanCaicedo** [comment]
@Aigeec related to your comments on https://github.com/jimhigson/oboe.js/pull/156

**Comment by Aigeec** [comment]
Yes, was going to suggest exactly that prettier + lint-staged. 

I do find something like eslint can be handy for productivity too with the right ide.

**Comment by Aigeec** [comment]
Do you want to go with vanilla prettier or standard? I like semi-colons :)

**Comment by JuanCaicedo** [comment]
I'm using no semicolons now, but don't feel strongly about it, so semistandard works for me if you want to use that. 

For prettier, I tend to use `--single-quote --trailing-comma es5`, but again I don't feel strongly about it

**Comment by Aigeec** [comment]
That's grand. Will just go with standardjs. 
Working through the issues that it's throwing up like '==' vs '===' etc. Will push something up when there are no errors.
