### ISSUE TITLE
done() called multiple times when using with flask streamed response

### ISSUE THREAD

**Issue by timfeirg** [jimhigson/oboe.js#124]
So I have this python flask code that generates json stream response (docs and examples see [here](http://flask.pocoo.org/docs/0.11/patterns/streaming/) and [here](https://blog.al4.co.nz/2016/01/streaming-json-with-flask/), the result is somehow different from all the examples I learned in [oboe.js examples](http://oboejs.com/examples).

```python
from flask import Response, Flask
import json

app = Flask(__name__)

@app.route('/test-json-stream.json')
def generate_json_stream():
    def generate():
        for i in range(5):
            yield json.dumps({'number': i, 'foo': 'bar'})
    return Response(generate(), mimetype='application/json')
```

And this is the corresponding javascript code that uses `oboe.js` to handle the response:

```javascript
  oboe({url: url, method: 'POST', body: data})
    .node('*', function(r){
      console.log(r);
    })
    .done(function(r) {
      console.log(r);
    })
```

Tested in my browser, I found that `.node()` is called 5 * 2 times (because there were two members in each JSON object) and `.done()` is called 5 times, so I wouldn't know when the request is actually terminated, is there any way to add some sort of *global callback* to the initial `oboe(url)` call? Just so I could be able to do something when the request is actually finished?

**Comment by timfeirg** [comment]
I read the code and found that there's a `'end'` signal to listen to.

**Comment by binarykitchen** [comment]
@timfeirg how? i am keen to know how to listen to the end signal

**Comment by timfeirg** [comment]
something like this @binarykitchen :

```javascript
  oboe({url: url, method: 'POST', body: data})
    .done(function(r) {
      console.log(r);
      if (r.error) {
        console.log('Got error', r);
        success = false;
      } else if (r.type == 'sentence') {
        logDisplay.append(r.message + '\n');
      } else {
        logDisplay.append(JSON.stringify(r) + '\n');
      }
      $(window).scrollTop($(document).height() - $(window).height());
    }).fail(function(r) {
      console.log(r);
    })
    .on('end', function() {
      console.log('Got end signal, success:', success);
      }
    })
```
