### ISSUE TITLE
Can't Pass POST Vars

### ISSUE THREAD

**Issue by TomAshley303** [jimhigson/oboe.js#130]
I've tried so many different ways of passing POST parameters. I'm working off the following example. I'm trying to do long-polling so I can show the progress of my PHP file's actions...

```
oboe('/api/',{method:'POST'},'',{action:'addPool'})
            .node('foods.*', function (foodThing) {

                // This callback will be called everytime a new object is
                // found in the foods array.

                console.log('Go eat some', foodThing.name);
            })
            .node('badThings.*', function (badThing) {

                console.log('Stay away from', badThing.name);
            })
            .done(function (things) {

                console.log(
                    'there are', things.foods.length, 'things to eat',
                    'and', things.badThings.length, 'to avoid');
            });
```

**Comment by JuanCaicedo** [comment]
Can you try passing a config object to `oboe` like the first example in the [api docs](http://www.oboejs.com/api)? If that doesn't work, I'm glad to help, but it would be best if you asked on stackoverflow so more people will find it. We mention some this in [contributing.md](https://github.com/jimhigson/oboe.js/blob/master/CONTRIBUTING.md#questionshelp)
