### ISSUE TITLE
 Reading a 500M json file using oboe.js will fail even when using oboe.drop

### ISSUE THREAD

**Issue by cnyzgkn** [jimhigson/oboe.js#131]
My code is like:
function testOboe() {
    oboe('result.json')
    .node('!.*', function(myObject){
    document.writeln(myObject["globalId"]);
        return oboe.drop;
    }).done(function(finalJson){
    document.writeln("load complete!");
    })
}

**Comment by JuanCaicedo** [comment]
Thanks for reporting! I'm going to close since it's a duplicate of https://github.com/jimhigson/oboe.js/issues/68
