### ISSUE TITLE
piping oboe output to node response object

### ISSUE THREAD

**Issue by foundling** [jimhigson/oboe.js#134]
I'm unsure about how to pipe data from the oboe node event to an express response stream.  I see that someone asked this question in 2014 (issue #47), but there isn't a solution.  Any idea how I can do this?  This is the code I have:

````
const express = require('express');
const app = express();
const PORT = 3000;
const oboe = require('oboe');
const fs = require('fs');

app.get('/download', (req, res) => {

    const jsonDataStream = fs.createReadStream('./citylots.json');

    oboe(jsonDataStream)
        .node('features.*', function(feature) {
           // res.send is non-streaming. how to stream?
            res.send(feature);
        });
});

app.listen(PORT, () => console.log(`up on port ${ PORT }!`));
````

**Comment by JuanCaicedo** [comment]
Hi @foundling! Thanks for your question 😃 Would you mind asking it on stackoverflow and linking her? I'm more than glad to help, but as mentioned in our [contributing doc](https://github.com/jimhigson/oboe.js/blob/master/CONTRIBUTING.md#questionshelp), that's the preferred method
