### ISSUE TITLE
[TASK] move to webpack

### ISSUE THREAD

**Issue by DanielRuf** [jimhigson/oboe.js#148]
Grunt is vurrently not the best solution, especially for larger projects.

webpack brings native streaming, less issues regarding parallel tasks and task sequences, treeshaking, ES6 features, more stable and faster build system, better support, ...

For browsers we can use babelify or babel with the needed ES2015 presets or the new env preset.

**Comment by JuanCaicedo** [comment]
This is related to what I mentioned in https://github.com/jimhigson/oboe.js/issues/129. I think it's definitely the right way to go, but I'm not sure about how to get there

**Comment by JuanCaicedo** [comment]
I think https://github.com/jimhigson/oboe.js/issues/148 would provide some great improvements, but I'm not sure about how to get started since I think it may involve working through a lot of the code. Doing that would probably pave the way for some better testing and dev process  improvements, which I think are the biggest blockers to getting new contributions and towards bugs/feature work

**Comment by DanielRuf** [comment]
I'll try to find the wright solution and describe the advantages and disadvantages. Especially babelify, Rollup, webpack and so on.

**Comment by JuanCaicedo** [comment]
I think there might be a way to bundle with webpack even if each file exposes it's functions globally. If that's the case, we could move to a webpack build without needing to change the code all at once and then update the files one by one

**Comment by DanielRuf** [comment]
I'm currently looking into Rollup and work on a plan. I would start and remove Grunt as dependency using only npm scripts.

Then I would convert the source files to ES6 modules and add babelify. Then we can decide if webpack, Rollup or something else should be used.

**Comment by JuanCaicedo** [comment]
I like the idea of moving things off of Grunt and to NPM, I've done this with a few commands like the test running. If you find yourself having to do lots of nested commands, you might find [this module scripty](https://github.com/testdouble/scripty) useful. 

I agree that Rollup seems like the right choice. I like that it can do tree shaking if your dependencies are ES modules. Some of the notes on <http://www.oboejs.com/> mention that having the library be small is a big goal, which tree shaking would help with. It would also let us remove clarinet from the src code and use it as a dependency, though it looks like [the project isn't actively maintained](https://github.com/dscape/clarinet)

**Comment by DanielRuf** [comment]
Scripty looks indeed interesting and helpful. So far I try to move the Gruntfile to separate js files which are defined as npm scripts.

From this point I'll check and evaluate scripty to see how it can ease the overall build process.

**Comment by JuanCaicedo** [comment]
@DanielRuf How has this gone for you? No problem if you're pretty busy, just wanted to make sure that you're not stuck and that I can offer help if possible

**Comment by DanielRuf** [comment]
So far I had not much time but I could do it this week.

**Comment by JuanCaicedo** [comment]
No pressure! Let me know if you need help 😀

**Comment by DanielRuf** [comment]
> No pressure! Let me know if you need help

Any help is very welcome. I've pushed a WIP PR #155, the other npm scripts also need some refactoring.
After taking this to pure npm scripts I would add ES6 modules to the next milestone which is another rewrite / refactoring. With this we can then use webpack for treeshaking and custom builds.

What do you think?

**Comment by JuanCaicedo** [comment]
That plan SGTM

**Comment by Aigeec** [comment]
Rollup is considered more appropriate for libraries where webpack is more for apps. Anything in particular I can take?

**Comment by Aigeec** [comment]
Is there a lint config to match the style that's used? It is a particular style and I think it may be difficult to maintain.

**Comment by DanielRuf** [comment]
> Rollup is considered more appropriate for libraries where webpack is more for apps. Anything in particular I can take?

Not in general. Webpack 3 and 4 also work great for libraries.

> Is there a lint config to match the style that's used? It is a particular style and I think it may be difficult to maintain.

What exactly do you mean?

**Comment by Aigeec** [comment]
> What exactly do you mean?

Looking through the code the formatting is unusual but does seem fairly consistent. I was just wondering if there were any lint rules captured (for example using eslint) to help contributors match the existing code style.

**Comment by Aigeec** [comment]
Webpack is based on imports and requires so using it will need the code to be modularised. While at the moment the code is in pieces they really just snippets are not something that Webpack or Rollup could work with. Certainly not to get any of the advantages that you have talked about. 

Looking at the code they generally seem to encapsulate a function or too. So these could be exported. You would then look at importing their dependencies and see where that gets you. Some of it will have to be refactored.

You could then look at unit testing the individual modules.

Are you planning es6 modules? Are you planning on using babel or typescript?

On the plus side the test suite that you have now should still run against the bundled code as a set of integration tests but it might take us a while to get there :)

**Comment by DanielRuf** [comment]
@Aigeec see https://github.com/jimhigson/oboe.js/pull/155/files

**Comment by Aigeec** [comment]
I had a look at that. You are doing some good work removing the dependency on grunt. It doesn't seem to move you towards using a bundler though. Is that something I should look at? 

You may need to refactor some of the build.js work that you are doing afterwards as it would no longer be necessary as the bundler would be doing that work.

**Comment by Aigeec** [comment]
I'll start work on that. I don't think it will actually take that long. The functions are defined and encapsulated they just need to be exported and then imported as necessary. They we can use webpack or rollup to bundle.

**Comment by Aigeec** [comment]
I have most of the work done on this now. It bundles with rollup (was quickest to just see if it bundled). Only thing to sort out really is picking the correct `streamingHttp` and `httpTransport` for the environment.

Will push it up tomorrow and you can have a look.

**Comment by JuanCaicedo** [comment]
This has been closed with https://github.com/jimhigson/oboe.js/pull/156. Great work @Aigeec !

**Comment by DanielRuf** [comment]
Awesome @Aigeec
