### ISSUE TITLE
[TASK] move to org

### ISSUE THREAD

**Issue by DanielRuf** [jimhigson/oboe.js#151]
We should move oboe.js to an organization to lower the truck factor, ease access and rights management for new maintainers and contributors and also increase the visibility of oboe.

**Comment by JuanCaicedo** [comment]
I wouldn't be opposed to this, but I'm not sure what @jimhigson would prefer and he's the only one with permissions to add new collaborators

**Comment by JuanCaicedo** [comment]
BTW, I had thought of this a while back and registered [oboejs](https://github.com/oboejs) as an organization, so we do have it 😄

**Comment by JuanCaicedo** [comment]
I was actually thinking to work on this tomorrow morning 😄 Thanks for hanging in there, I really appreciate your contributions

**Comment by JuanCaicedo** [comment]
I reached out to Jim about this since I am a collaborator and not an owner of the repo. I'll update here if we move things over 👍

**Comment by DanielRuf** [comment]
> choose to host in a different way

Would GitHub pages work here or be a possible solution?

**Comment by DanielRuf** [comment]
Hi @jimhigson,

thanks for your reply and the feedback. I think these are good recommendations and this is what I also had in mind (mention you as creator and longterm / previous maintainer and link to the original repository).

> choose to host in a different way

Would GitHub pages work here or be a possible solution?

**Comment by jimhigson** [comment]
The current site generates html from markdown on the fly using
node/express. It would take a little work to get it onto github pages since
that would need it to be static html but I don’t see why it couldn’t be
done. Probably the simplest way would be to write a small script to scrape
the site into a static version. This would have to be run every time the
markdown is changed.

**Comment by DanielRuf** [comment]
Or we use Travis CI + the gh-pages package (just an idea).

**Comment by JuanCaicedo** [comment]
I've been doing a lot of hosting with [Zeit Now](https://zeit.co/now), I think it's free for OSS
