### ISSUE TITLE
Oboe runs node after all the data is loaded

### ISSUE THREAD

**Issue by dkaushik95** [jimhigson/oboe.js#176]
I am trying to run oboe in a react-native app 
```
oboe({url: url, headers: options.headers})
    .node('!.[*]', (data) => {
      console.log(data)
    }).start(headers => {
      console.log(headers);
      this.statusText = "Getting data..."
      // this.toggleLoading(true);
    })
    .done(response => {
      console.log("Done")
      this.incidentLoading = false;
      this.statusText = "Data loaded"
    })
    .fail(error => {
      console.log(error);
      this.statusText = "Error getting data"
      this.toggleLoading(false);
    })
```

What happens that the `node` function runs after I get all the data in. The expected behavior should be to get parts of the data in. Am I doing something wrong here?

**Comment by Aigeec** [comment]
Please provide an example of the data being processed.

**Comment by dkaushik95** [comment]
My data is similar to this : 
```
[
{fields: values},
...
]
```

I tried that pattern, and in the node, I am actually updating the view, but the view is updated only when the node reaches done.

**Comment by Aigeec** [comment]
In general when raising an issue it is best to provide a jsfiddle (or similar) of the issue in it's simplest terms.

I have take then liberty to do one for you with oboe and the data you have specified.

https://jsfiddle.net/t6akqL91/54/

This behaves as expected.

**Comment by dkaushik95** [comment]
I figured out the problem, there was something wrong with mobx with Symbols. Mobx works great! Thanks @Aigeec
