### ISSUE TITLE
Logo does not render correctly on certain screens

### ISSUE THREAD

**Issue by fulldecent** [jimhigson/oboe.js#184]
The logo in logo.png is rendered with specific assumptions about the display's sub-pixel layout. And it will render not as intended when loaded on other monitors.

Recommendation. Open in GIMP, change color channels to grayscale, save.

**Comment by haysclark** [comment]
@fulldecent Why not make a PR with your solution?

**Comment by fulldecent** [comment]
I have not contributed here yet. Waiting for +1 from someone with commit access, then I can make a PR.

**Comment by Aigeec** [comment]
Go for it

**Comment by fulldecent** [comment]
Fixed at https://github.com/jimhigson/oboe.js/pull/200
