### ISSUE TITLE
JSON-in-JSON causes the oboe parser to stumble

### ISSUE THREAD

**Issue by reactormonk** [jimhigson/oboe.js#194]
Sample code:

```
const Readable = require('stream').Readable;
const s = new Readable();
s._read = () => {}; // redundant? see update below

const oboe = require('oboe');
const r = oboe(s);
r.on("done", console.log);

s.push('{"hello": "there"}'); // this one logs

const json = '{"log":"{\"level\":\"debug\",\"transformationError\":\"Something went wrong\"}","stream":"stdout","time":"2019-09-19T07:22:33.363566344Z"}';
s.push(json); // this one doens't

```

**Comment by Aigeec** [comment]
The json you are sending is two separate objects. Oboejs parses a single
object. So as far as it was concerned it was 'done' after first object.

Try putting it in an array, i.e. send a [ then one of your objects followed
by a , repeat until you are done and finish with ].

You would want to event on each node.

A

**Comment by reactormonk** [comment]
Right, forgot the level of escape I have to put it through.
