### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by djanowski** [jimhigson/oboe.js#246]
http://oboejs.com

**Comment by 4D5A90** [comment]
Any news ?

**Comment by 7hibault** [comment]
Seems it's been that way for a while, the most recent wayback machine snapshot is august 2021 https://web.archive.org/web/20210814153523/http://oboejs.com/

**Comment by the-dansan** [comment]
The github repo for the website is around. That's what I use. But yeah, the owner of this repo has been out of things for a bit, it seems.

**Comment by irsl** [comment]
Heroku has discontinued their free plan end of November, 2022.

**Comment by sheldonmaschmeyer** [comment]
`clarinet` and `sax-js` have not been updated in 2 years.
Oboe is primarily maintained by: https://github.com/jimhigson
However, he has been busy working on private repository (presumably a paid job).
There is no way to directly fund development.
Perhaps there is a 2023 maintained alternative?

**Comment by dmoojunk** [comment]
You can look at his public website code, happily in markdown format here - https://github.com/jimhigson/oboe.js-website/blob/master/content/examples.md

**Comment by jimhigson** [comment]
This is long overdue a reply, but I've resurrected it (with an archival notice) - it is now readable back at the original [oboejs.com](http://oboejs.com) - or will be in a few hours when the DNS propagates

**Comment by jimhigson** [comment]
@sheldonmaschmeyer 

> clarinet and sax-js have not been updated in 2 years.
> Oboe is primarily maintained by: https://github.com/jimhigson
> However, he has been busy working on private repository (presumably a paid job).

Even worse than that I'm afraid - a paid job, plus fatherhood! 👧🏻👶🏻

Honestly, I'd love to make a modern equivalent, or help someone else to.
