### ISSUE TITLE
Working with streaming JSON

### ISSUE THREAD

**Issue by joneshf** [jimhigson/oboe.js#42]
This is partly a question, but might also be a possible bug or point of confusion, so I figured I'd ask here rather than the google group. I didn't see any guidelines on where to ask stuff, so this seemed like the best place. If you'd like to move the conversation there, let me know.

I just started using oboe with a server that streams json responses. It streams each object separately.

So, something like:
```json
{
  "foo": 3,
  "bar": "BAR!!"
}
```

So far oboe is able to work with the results and each object separately, and most of the examples work well. However, when trying to follow an example with a `done` callback, it seems to fire the `done` event every time it receives an object. Is this how it's supposed to be? 

My interpretation of it was that the event is only fired once the entire response is completed. But it seems like it's treating each object as its own response. Is it behaving differently because the server is actually streaming json rather than returning a single json object? Or could something else be at play here? Am I using it improperly?

Let me know if there's any information you might need.

**Comment by joneshf** [comment]
At this point it's over, so this isn't a concern for me anymore.

Thanks for the ideas and assistance though.

**Comment by glortho** [comment]
I take it there hasn't been any movement on this, or plans to do so? https://github.com/jimhigson/oboe.js/issues/42#issuecomment-46701521

**Comment by stonecrafter** [comment]
Also curious about whether this feature will be added.
