### ISSUE TITLE
Streaming JSON to express

### ISSUE THREAD

**Issue by darkenspirit** [jimhigson/oboe.js#47]
I have oboe pulling out the objects I want from the readstream but I dont know how to pipe it back to res?

app.get('/foo', function(req, res) {
var rstream = oboe(fs.createReadStream("./test");
rstream.node( "{}", function(data) {
        if ( data.test != undefined ) {
            >>>> now what?

rstream has no method pipe so I cant simple
rstream.pipe(res) at this point.

If i try the example with streaming HTML with JSON service, I get an error saying no engine or extension provided when creating a new view.

I am really not sure how to proceed here

**Comment by foundling** [comment]
@darkenspirit did you ever figure this out? I'm also curious about piping to res instead of building all of the data in memory.
