### ISSUE TITLE
There is no "end" to complement "start".

### ISSUE THREAD

**Issue by jessegit** [jimhigson/oboe.js#49]
This is a case of many JSON objects concatenated. (Generated by a service on the internet, not much I can do about it). In my case I'm interested in knowing when the HTTP request is done (marks an end of a 'list'), but there appears to be no way to tell. There is a "start" at the beginning of the request, with "done" after each object in the stream, but nothing after the HTTP request has finished. Everything else seems to work well.

The only reason I'm using oboe is that it was the only thing I could find that would even parse the data to begin with...

**Comment by ArtworkAD** [comment]
Should be closed in favour of https://github.com/jimhigson/oboe.js/issues/44 ?

**Comment by jessegit** [comment]
If #44 is leading to some kind of a start,object_done,object_done,...,request_done design, I see no reason to keep this open separately.
