### ISSUE TITLE
Can't use oboe in HTML5 web worker

### ISSUE THREAD

**Issue by ScreenDriver** [jimhigson/oboe.js#58]
Is there a chance to use oboe in a HTML5 web worker? If I try to load use it I get a

```JavaScript
ReferenceError: window is not defined
```
because in web workers you can't access the window object. My JSON file is extremely large so I can't process all this stuff in the GUI thread.

**Comment by jimhigson** [comment]
Ah yes, this certainly worked in the past and looks like a bug. As a quick
workaround you could try loading the node version (although this requires
browserify) but should really be fixed.

Would you be able to make a PR? Should be fairly easy to find where window
is being used and make it optional. Off the top of my head, I imagine this
is the CORS code.

**Comment by ScreenDriver** [comment]
Hmm I don't know how exactly I should fix it. [Here](https://github.com/jimhigson/oboe.js/blob/master/src/wrapper.browser.js#L14) you attach ```oboe``` the global ```window``` object. But in web workers there is no window object. How would you handle this? Would you make ```oboe``` as a global variable?

**Comment by jimhigson** [comment]
I suspect that the correct way would be (window|self).oboe = oboe; for that
line but I'm on my iPad now so I can't test that.

IIRC, that would work in a normal page or a worker thread.

Could you try and see if it works? If it does make a PR and I'll merge when
the tests pass on travis.

**Comment by jimhigson** [comment]
Fixed in v2.1.1
