### ISSUE TITLE
Get Oboe instance in a bounded callback?

### ISSUE THREAD

**Issue by gsklee** [jimhigson/oboe.js#60]
Is there any way to refer to the Oboe instance if I'm working with a bounded callback?

```javascript
oboe({
    url: this.props.url
}).node('user', (user) => {
    this.setState({
        user: user
    });

    // And I'd like to do .abort() here
})
```

**Comment by gsklee** [comment]
BTW I'm talking about some better way other than the very old school `var self = this` workaround.

**Comment by jimhigson** [comment]
Ah, I see. There isn't any way at the moment but there probably should be.
What do you think this should look like?

Perhaps something like assigning oboe.instance to the instance that called
the callback? This would only be available for the duration of the callback.

**Comment by gsklee** [comment]
@jimhigson That would be great, yeah.

**Comment by gsklee** [comment]
@jimhigson To somewhat strengthen my reasoning, @rauschma suggested in [this article](http://www.2ality.com/2012/04/arrow-functions.html) that callbacks are subroutines and would be better expressed as arrow functions.

To complement your proposal, here is another idea - assign the instance as a parameter of the callback:

```javascript
oboe({
    url: this.props.url
}).node('user', (user, instance) => {
    this.setState({
        user: user
    });

    instance.abort();
})
```

**Comment by JuanCaicedo** [comment]
I know Bluebird has a pretty useful [bind](http://bluebirdjs.com/docs/api/promise.bind.html) method. You basically bind the first function, and then that scope follows through all the functions you chain on it. 

If we did this in oboe, I think it would look kind of like this:

```javascript
oboe({
    url: this.props.url
  })
  .bind(this)
  .node('user', function(user) {
    this.setState({
      user: user
    });
    // And I'd like to do .abort() here
  });
```

**Comment by gsklee** [comment]
I don't think that's some good API design, honestly. If there's little consensus I guess we can keep the way it is now.
