### ISSUE TITLE
Doesn't recognize some node streams - checks for 'unpipe' and 'unshift' which many not exist

### ISSUE THREAD

**Issue by ralphmason** [jimhigson/oboe.js#65]
Using request in node (https://github.com/request/request)

var stream = request(blah..);
oboe(stream) // Doesn't think stream is a stream 
       .on("farb",....)

This is because it checked for 'unpipe' and 'unshift' to determine if it had a stream or not.
 I removed the check for those functions as below and all worked fine.

var nodeStreamMethodNames = list('resume', 'pause', 'pipe' ); //,'unpipe','unshift'),

**Comment by mbakaitis** [comment]
I have a similar issue...but I think this might be more of a problem with request than with oboe?  

See the request issue on that project's site that was opened in April 2014:  [Object #<Object> has no method 'unpipe' #874](https://github.com/request/request/issues/874)

**Comment by jimhigson** [comment]
Agree: this *does* look like an issue with request, but in practice I can't see any problem with accepting a stream that doesn't have `unpipe` and `unshift` methods. Request's pseudo-pipe is still distinct enough from anything else `oboe()` would be expected to accept.

Will push out a new patch version with this change.

**Comment by jimhigson** [comment]
See [here](http://oboejs.com/api#byo-stream)
