### ISSUE TITLE
Are there any way to use oboe to upload files?

### ISSUE THREAD

**Issue by nhducit** [jimhigson/oboe.js#70]
My api received upload file through FormData, and streaming response

How do I can send files using oboe? 

I see this line in source code:
line 2435:
body = JSON.stringify(body);

it seems I can not send from data with oboe.

**Comment by JuanCaicedo** [comment]
I don't think you can send files using oboe, but you could parse a file that you are receiving. 

Is the uploaded file you're receiving a readable stream? If so, you should be able to pass it to Oboe on the server side.

**Comment by Aigeec** [comment]
I think the use case here is that the api that is being used expects a file to be uploaded then streams are response.

I'll add the same logic as @rotu to check if its form data. 

Can we roll #146 (as I'd have to add specific logic in for FormData as is easier to remove it) into this as well and remove the content-length headers? Is the Content-Length header added for making requests in Node? If so could we move it to [streamingHttp.node.js](https://github.com/jimhigson/oboe.js/blob/master/src/streamingHttp.node.js)
