### ISSUE TITLE
oboe with datas ?

### ISSUE THREAD

**Issue by Sashkan** [jimhigson/oboe.js#76]
Is 'data' handled by oboe.js ?

I've been using oboe to stream response from an API. Everything works great with all of the calls that does not require parameters, but how can I work with parameters-dependant calls ?

```js 
// basic ajax request for my call is
$.ajax({
  dataType: "json",
  url: url,
  data: data,
  success: success
});
// 'data' is my parameters list, as a json string. How can I pass it to oboe ?
oboe(url)
            .done(function(things) {
                alert('success');
                console.log(things);
            })
            .fail(function(test) {
                alert( "ERROR:  " + test );
                console.log(test);
            });
```

**Comment by JuanCaicedo** [comment]
You can pass a configuration object into the `oboe` function, the pass your data as the request body (you might have to format this according to how the API expects it). There's more details in http://oboejs.com/api

**Comment by Sashkan** [comment]
Thank you ! I did it this way, and I got some weird error:
- When I call to a simple API function, that is supposed to send me an integer, it works just fine.
- When I call to a function that expects parameters, and DO NOT fill these parameters, it works (I got the correct response, without datas, obviously).
- When I call to that same function, and fill parameters using the request body, it fails.

This is how I call my function:
``` js
oboe({
            url: url,
            body: search,
            method: 'POST'
        })
                .done(function(things) {
                    console.log(things);
                })
                .fail(function(test) {
                    console.log(test);
                });
```

url is a valid url, search is a json-encoded object.
and this is the error:

``` 
OPTIONS http://middle.openjetlab.fr/app_dev.php/api/rests/requests/availabilities 405 (Method Not Allowed)
streamingHttp @ main_oboe-browser_14.js:1317
wire @ main_oboe-browser_14.js:2569
applyDefaults @ main_oboe-browser_14.js:2627
oboe @ main_oboe-browser_14.js:2662
(anonymous function) @ results?results[0][lfi_from]=DA44220&results[0][lfi_to]=GM57501&results[0][datetime]=2015-10-30+00%…:109
results?results[0][lfi_from]=DA44220&results[0][lfi_to]=GM57501&results[0][datetime]=2015-10-30+00%…:1 

XMLHttpRequest cannot load [my url]. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://openjetfrontclean' is therefore not allowed access. The response had HTTP status code 405.
```

**Comment by JuanCaicedo** [comment]
I think this question is better fit for stackoverflow. I've posted it [there](http://stackoverflow.com/questions/34773529/how-to-pass-data-to-oboe-js/34773548#34773548)
