### ISSUE TITLE
Transform js object/array

### ISSUE THREAD

**Issue by ahamid** [jimhigson/oboe.js#79]
Is there a way to use oboe transformation functionality with existing javascript objects (not JSON strings)?  It looks like oboe is dependent on events emitted by clarinet which is a JSON parser.  I assume it would take a replacement of clarinet that simply walked the object tree (assuming it's not a graph) and emitted similar events?

**Comment by JuanCaicedo** [comment]
I think you could either stringify the JSON and pass it as a stream to Oboe, or you could use a library like [Highland.js](http://highlandjs.org/) to turn the object into a stream.

**Comment by JuanCaicedo** [comment]
Do you think that would work for you @ahamid?

**Comment by ahamid** [comment]
Hi @JuanCaicedo, probably not as my goal with Oboe would be to walk a gigantic object graph which I wouldn't want to reserialize back into JSON.  That's ok, I was just curious and have moved on.
