### ISSUE TITLE
Question about chainable method and retrieving ancestor value

### ISSUE THREAD

**Issue by DomSavd** [jimhigson/oboe.js#92]
Firts of all thanks for that great plugin!

I have a json file (see example below) and i want to retrieve data  from the node "sections"  and also map the ancestor profile_namespace and owner_name to the data retrieve from sections node. Right now i am only able to retrieve data from  the node "sections" but i saw in the documentation that .node return chainable method and that it is possible to use the notion of "ancestors" to retrieve data from the parent. Does anyone can explain me how to use this method (see my code below)?

**JSON EXAMPLE:**
{
	"data": [
		{
			"profile_namespace": "DS",
			"tutorial": {
				"owner_name": "Dominic",
				"picture_url": "/picture.jpg",
				"title": "The code",
				"url": "/Dominic/thecode/",
				"sections": [
					{
						"episode_url": "/tutorial/intro/symphony-of-war/",
						"artist": "MasterOrchestra",
						"title": "Symphony of War"
					},
					{
						"episode_url": "/tutorial/mainshow/musicproductiontip1/",
						"artist": "DStone",
						"title": "Music production tip 1"
					},
					{
						"episode_url": "/tutorial/outrothe/nextshow/",
						"artist": "MasterOrchestra",
						"title": "Next show"
					}
				
				]
			}
		}
      ] 
 } 

**CODE**
var oboe = require ('oboe');
var fs = require('fs');
var SetList = require('fs');
var setList =[]; 
var showInfo = require('fs');

oboe(fs.createReadStream('/myjson.json'))
   .node({
      'sections': function(node){
        setList.push(node);
        showInfo = fs.createWriteStream('/showInfo.json');
        showInfo.write(JSON.stringify(setList)); 
      }
   });

**Comment by JuanCaicedo** [comment]
Hi @DomSavd, think your question might be a better fit for Stackoverflow (this is outline in the [upcoming CONTRIBUTING.md](https://github.com/jimhigson/oboe.js/pull/91). 

If you want to open up a question on there and link to it here, I'd be more than happy to help! :smile:

**Comment by DomSavd** [comment]
Thanks for your answer! I just post my question to stackoverflow and hoping to get some help. My code is now formated to ;)

Here is the link: http://stackoverflow.com/questions/35435543/oboe-js-how-to-work-with-chainable-method-and-retrieving-ancestor-value

After getting my answer, ill see if i can submit an enhancement for the actual documentation. I think there sould be more example for people like me ;)

Thanks again!

**Comment by JuanCaicedo** [comment]
I agree with you that it's not really clear in the API, I was actually recently confused about what those two other arguments are. I'm not sure how they would be better documented, but definitely feel free to make a PR to the [oboe website](https://github.com/jimhigson/oboe.js-website). I would love to see what you come up with! :smiley:
