### ISSUE TITLE
oboejs.com not running

### ISSUE THREAD

**Issue by getglad** [jimhigson/oboe.js#97]
The website is down - looks like you were using Nodejitsu, which I think was going away after being bought by GoDaddy. Maybe look at transitioning to a github.io site? Happy to help if you need some backup

**Comment by JuanCaicedo** [comment]
I noticed this as well and I've reached out to Jim about it. I like the idea of doing a github pages version too. Thanks for offering to help @getglad!

I was thinking of making a github organization named `OboeJS` and then making the organization page the main site. The only thing that I think will require some work is that the [website](https://github.com/jimhigson/oboe.js-website) is currently a node app, so we'll have to transition it to a static page site.

**Comment by getglad** [comment]
Maybe it would be worth grabbing a free tier on Nitrous (or something similar) https://www.nitrous.io/pricing/

**Comment by JuanCaicedo** [comment]
I do like the idea of gh-pages so anyone can contribute to the site and anyone with access to the repo can update it, but that sounds like a fantastic short term fix! I'm going to look into that tonight and can post a link

**Comment by getglad** [comment]
Sounds good - I'll take a look at the website repo when I have some time later - see if I can find a path to a static version

**Comment by jimhigson** [comment]
Hey, just got on this. Nodejitsu looks like it is still running after the
GoDaddy buy out. Like the ideas here, but will try to get the site back in
the meantime.

**Comment by jimhigson** [comment]
The website is back now. Was stopped on jitsu and fixing was just a matter
of clicking 'start'. Logs don't show any problems. Please reopen if this
happens again.
