### ISSUE TITLE
Oboejs.com is unavailable to public

### ISSUE THREAD

**Issue by vasco3** [jimhigson/oboe.js#99]
The website requires a username and password.

<img width="817" alt="screen shot 2016-03-14 at 3 42 46 pm" src="https://cloud.githubusercontent.com/assets/804301/13762324/6cd56a40-e9fb-11e5-8b43-500ddc337782.png">

**Comment by JuanCaicedo** [comment]
I noticed that too, which was strange, but could you try going to www.oboejs.com? I think that fixes it. Strange behavior which is probably worth fixing though

**Comment by vasco3** [comment]
it worked when I used https

**Comment by vasco3** [comment]
maybe the ssl expired

**Comment by jimhigson** [comment]
This is odd. I get a page that says "A portfolio site for Lief Strider's
drawings and illustrations. Coming soon…" - I still own that domain. Maybe
a problem (again) with jitsu, I'll try restarting the site.

**Comment by jimhigson** [comment]
Restarted the webapp on nodejitsu and looks ok now. However, Nodejitsu seems to be getting less and less reliable recently. A static site on github.io may be the way forwards.
